services:
  # Next.js アプリケーションサービス(本番環境)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # ビルド時に必要な環境変数を渡す
        DATABASE_URL: ${DATABASE_URL}
    container_name: todo-app
    environment:
      # 実行時の環境変数を設定
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV:-production}
    depends_on:
      - postgres
    networks:
      - todo-network
    restart: unless-stopped
    # standalone モードでは server.js が実行される (CMD で指定済み)

  # nginx ウェブサーバー
  nginx:
    image: nginx:alpine
    container_name: todo-nginx
    ports:
      - "80:80" # HTTP トラフィック(拒否)
      - "443:443" # HTTPS トラフィック(SSL/TLS)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # nginx 設定ファイル
      - ./certs:/etc/nginx/certs:ro # SSL証明書ディレクトリ
    networks:
      - todo-network
    restart: unless-stopped

  # PostgreSQLデータベースサービス
  postgres:
    image: postgres:17-alpine # PostgreSQL 17系の最新マイナーバージョン
    container_name: todo-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # ローカルホストの5432ポートにマッピング
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 初期化SQL
    networks:
      - todo-network
    restart: unless-stopped

volumes:
  postgres_data: # データの永続化用ボリューム

networks:
  todo-network: # アプリケーションとデータベース間のネットワーク
    driver: bridge
